### ISSUE TITLE
请问浦东的车怎么弄的？

### ISSUE THREAD

**Issue by wuxiaoq** [gyfstephen/shanghai-bus#3]
现在bus的number固定是数字。
一些特殊名字的怎么弄？
比如 浦东11路，张江环线等。

**Comment by wuxiaoq** [comment]
可以了，把  self.number = u'{0}'.format(number)  这一行中的“路”去掉
http://127.0.0.1:5000/api/v1/stops/up/张江环线/

**Comment by woo11051108** [comment]
这个我fork了之后没动过，因为先弄了个PHP可以用的了

**Comment by woo11051108** [comment]
这个我fork了之后没动过，因为先弄了个PHP可以用的了
